Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
sklearn.datasets.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [4]:
df = sns.load_dataset('iris')

In [5]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
df.describe()


sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [15]:
df['species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [17]:
##Converting categorical data into numerical we use label encoder as shown in folllowing
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [19]:
df['species'].head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int32

In [20]:
##Segerrate independent and Dependent Features
x = df.drop(labels=['species'],axis=1)
y=df.species

In [21]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [22]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=42)

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
classifier = KNeighborsClassifier(n_neighbors=5, algorithm="auto")
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [27]:
y_pred= classifier.predict(x_test)

In [28]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [30]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0  0]
 [ 0 15  1]
 [ 0  0 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        15

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [ ]:
Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in
sklearn.datasets.

In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [39]:
import statsmodels.api as sm
df1 = sm.datasets.get_rdataset('Boston', package='MASS').data
df1.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [41]:
df1.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio       black  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [45]:
# Segreggate independent andDependent Variable
y = df1['medv']
x = df1.drop('medv',axis=1)

In [46]:
x

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [47]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [48]:
from sklearn.model_selection import train_test_split

In [52]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=42)

In [55]:
from sklearn.neighbors import KNeighborsRegressor

regressor = KNeighborsRegressor(n_neighbors=5, algorithm="auto")
regressor.fit(x_train, y_train)  # Assuming y_train contains continuous values for regression


KNeighborsRegressor()

In [56]:
y_pred= regressor.predict(x_test)

In [57]:
y_pred

array([24.54, 29.34, 14.6 , 28.94, 17.44, 31.88, 20.58, 16.06, 18.02,
       21.18, 21.9 , 21.36, 12.28, 20.56, 23.7 , 21.74, 21.18, 14.06,
       33.72, 10.6 , 25.86, 29.34, 19.7 , 21.08, 18.88, 23.16, 21.88,
       12.34, 21.9 , 21.18, 22.68, 23.14, 10.3 , 30.04, 17.54, 21.12,
       21.66, 22.92, 22.52, 29.08, 21.18, 27.98, 38.82, 22.4 , 24.84,
       12.6 , 19.7 , 28.94, 19.8 , 22.22, 22.44, 34.7 , 22.04, 21.18,
       29.72, 21.38, 12.5 , 35.04, 21.82, 20.6 , 25.3 , 38.82, 28.68,
       16.26, 30.46, 24.24, 12.24, 25.3 , 35.04, 12.34, 23.94, 22.52,
       14.82, 30.38, 20.56,  8.98, 19.68, 38.82, 10.94, 15.04, 22.4 ,
       15.96, 26.3 , 12.24, 22.02, 34.  , 14.16, 22.58, 26.04, 17.86,
       24.5 , 15.22, 17.48, 21.76, 24.76, 17.86, 30.16, 10.76, 10.76,
       11.92, 21.82, 20.56, 23.16, 21.28, 22.22, 10.88, 23.96, 24.56,
       26.74, 26.3 ,  9.98, 15.74, 23.46, 33.72, 33.46, 15.22, 27.9 ,
       17.2 , 22.76, 22.44, 24.78, 31.62,  9.78, 18.74, 24.38, 23.28,
       28.28, 24.22,

In [61]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


In [62]:
# Calculate and print regression metrics
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False))
print("R-squared:", r2_score(y_test, y_pred))

Mean Absolute Error: 4.148862275449102
Mean Squared Error: 32.17596886227545
Root Mean Squared Error: 5.6723865226441905
R-squared: 0.5748334691810936


In [ ]:
Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
cross-validation on load_iris dataset in sklearn.datasets.

In [63]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

# Load the dataset
iris = load_iris()
X = iris.data
y = iris.target

# Initialize a list to store cross-validation scores
cv_scores = []

# Define a range of k values
k_values = list(range(1, 21))

# Perform k-fold cross-validation for each k value
for k in k_values:
    knn_classifier = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn_classifier, X, y, cv=5, scoring='accuracy')  # 5-fold cross-validation
    cv_scores.append(scores.mean())

# Find the optimal k with the highest cross-validation score
optimal_k = k_values[cv_scores.index(max(cv_scores))]

print(f"The optimal value of k for KNN classifier is: {optimal_k}")


The optimal value of k for KNN classifier is: 6


In [ ]:
Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
sklearn.datasets.

In [68]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)



# Load the Boston Housing dataset from openml
boston = fetch_openml(data_id=531)  # Using the specific data_id for Boston Housing dataset

X = boston.data
y = boston.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize a StandardScaler
scaler = StandardScaler()

# Fit and transform the scaler on training data, and transform test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize KNN regressor
knn_regressor = KNeighborsRegressor(n_neighbors=3)

# Fit the regressor to the scaled training data
knn_regressor.fit(X_train_scaled, y_train)

# Predict on the scaled test set
y_pred = knn_regressor.predict(X_test_scaled)

# Calculate mean squared error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error of KNN Regressor with Feature Scaling: {mse}")


Mean Squared Error of KNN Regressor with Feature Scaling: 19.40428104575163


C:\ProgramData\anaconda3\lib\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
load_iris dataset in sklearn.datasets.

In [69]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load the dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize KNN classifier with weighted voting
knn_classifier_weighted = KNeighborsClassifier(n_neighbors=3, weights='distance')

# Fit the classifier to the training data
knn_classifier_weighted.fit(X_train, y_train)

# Predict on the test set
y_pred = knn_classifier_weighted.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of KNN Classifier with Weighted Voting: {accuracy}")


Accuracy of KNN Classifier with Weighted Voting: 1.0


In [ ]:
Q6. Implement a function to standardise the features before applying KNN classifier.

In [70]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

def knn_classifier_with_standardization(X_train, X_test, y_train, y_test, n_neighbors=3):
    # Initialize StandardScaler
    scaler = StandardScaler()

    # Fit and transform scaler on training data, transform test data
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Initialize KNN classifier
    knn_classifier = KNeighborsClassifier(n_neighbors=n_neighbors)

    # Fit the classifier to the scaled training data
    knn_classifier.fit(X_train_scaled, y_train)

    # Predict on the scaled test set
    y_pred = knn_classifier.predict(X_test_scaled)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    return accuracy

# Load the dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply the function to get accuracy using standardized features
accuracy = knn_classifier_with_standardization(X_train, X_test, y_train, y_test, n_neighbors=3)
print(f"Accuracy of KNN Classifier with Standardization: {accuracy}")


Accuracy of KNN Classifier with Standardization: 1.0


In [ ]:
Q7. Write a Python function to calculate the euclidean distance between two points.

In [71]:
import numpy as np

def euclidean_distance(point1, point2):
    # Ensure points are NumPy arrays for vectorized operations
    point1 = np.array(point1)
    point2 = np.array(point2)

    # Calculate Euclidean distance
    distance = np.sqrt(np.sum((point1 - point2) ** 2))
    return distance

# Example usage
point_a = [1, 2, 3]  # Example point 1
point_b = [4, 5, 6]  # Example point 2

# Calculate Euclidean distance between the two points
distance = euclidean_distance(point_a, point_b)
print(f"Euclidean Distance between point A and point B: {distance}")


Euclidean Distance between point A and point B: 5.196152422706632


In [ ]:
Q8. Write a Python function to calculate the manhattan distance between two points.

In [72]:
import numpy as np

def manhattan_distance(point1, point2):
    # Ensure points are NumPy arrays for vectorized operations
    point1 = np.array(point1)
    point2 = np.array(point2)

    # Calculate Manhattan distance
    distance = np.sum(np.abs(point1 - point2))
    return distance

# Example usage
point_a = [1, 2, 3]  # Example point 1
point_b = [4, 5, 6]  # Example point 2

# Calculate Manhattan distance between the two points
distance = manhattan_distance(point_a, point_b)
print(f"Manhattan Distance between point A and point B: {distance}")


Manhattan Distance between point A and point B: 9
